### ISSUE TITLE
Screen sharing while video calling

### ISSUE THREAD

**Issue by thegitparticle** [AgoraIO-Community/VideoUIKit-iOS#28]
Is your feature request related to a problem? Please describe.
Screen sharing while video calling.

Describe the solution you'd like
An options to share screen while talking with people. Here is the agora docs implementation of it - https://docs.agora.io/en/Video/screensharing_ios?platform=iOS

**Comment by maxxfrazer** [comment]
@thegitparticle can you suggest what you'd like to see for this feature? as shown in the docs it screen sharing requires an app extension etc, not sure yet how the best way to implement that through a library would be

**Comment by maxxfrazer** [comment]
Apologies for the delay on this one @thegitparticle. I've just added a product to this package that makes screen sharing very easy.

There's an example here: https://github.com/AgoraIO-Community/Video-UI-Kit-ScreenShare
And the DocC guide: https://agoraio-community.github.io/VideoUIKit-iOS/extensions/AgoraBroadcastExtensionHelper/documentation/agorabroadcastextensionhelper/quickstart/

**Comment by maxxfrazer** [comment]
Closing this issue, as screen sharing now works nicely with video ui kit 🚀 please reach out if there are any questions.
