### ISSUE TITLE
Some Methods are only available in iOS 13.0 or newer Error.

### ISSUE THREAD

**Issue by Premal-Khetani** [AgoraIO-Community/VideoUIKit-iOS#76]
**Describe the bug**
I have installed the pod, and I am facing some issues with the files. Like 

**'secondarySystemBackground' is only available in iOS 13.0 or newer**

**To Reproduce**
1. Create a project with target 13.0 and create pods
2. Install pods
3. Try to build.

**Expected behavior**
It should run without any error as my least target is 13.0

**Screenshots**

![Screenshot at Sep 08 12-49-18](https://user-images.githubusercontent.com/13691970/189059836-7aa93812-4204-4e3d-aeea-cec7f1f9c490.png)

**Smartphone (please complete the following information):**
 - Device: any iPhones
 - OS: iOS 13.0

**Comment by maxxfrazer** [comment]
The pod spec for this is also set to 13, so if it's earlier than 13 it shouldn't even get this far.

Could you check that the iOS deployment target is set to 13+ as shown here?
The Xcode version you're using (I'm sure it's a recent one), video uikit version. Also if it works fine for you with the example project included in this repo?

<img width="728" alt="Screenshot 2022-09-08 at 14 24 12" src="https://user-images.githubusercontent.com/5754073/189120894-4fd73fdb-a829-4a99-a576-a5ede9421f8e.png">

**Comment by maxxfrazer** [comment]
Going to go ahead and close this issue, the library is only compatible with iOS 13+ in any case.
