### ISSUE TITLE
Icons are undefined for macOS

### ISSUE THREAD

**Issue by rolf-mobeus** [AgoraIO-Community/VideoUIKit-iOS#82]
When building on macOS following instructions for minimal implementation, the icons are missing. 

From the code in UIButton+Extensions:
```
    #elseif os(macOS)
    /// SF Symbol name for camera icon for builtin button
    static var videoSymbol = "􀌟"
    /// SF Symbol name for camera alt icon for builtin button
    static var muteVideoSelectedSymbol: String?
    /// SF Symbol name for microphone icon for builtin button
    static var micSymbol = "􀊰"
    /// SF Symbol for microphone alt icon for builtin button
    static var muteMicSelectedSymbol: String? = "􀊲"
    /// SF Symbol for microphone muted flag
    static var micSlashSymbol = "􀊲"
    /// SF Symbol for flip camera builtin button
    static var cameraRotateSymbol = "􀌢"
    /// SF Symbol for beautify buitlin button
    static var wandSymbol = "􀜎"
    /// SF Symbol to appear behind user with camera off
    static var personSymbol = "􀓣"
    /// SF Symbol for sharing screen builtin button
    static var screenShareSymbol = "􀏧"
    /// SF Symbol for pin icon
    static var pinSymbol = "􀎧"
```

This seems like a bug, or at least it makes the example confusing.

**Comment by maxxfrazer** [comment]
@rolf-mobeus do you see the same thing when opening with quicklook or Xcode on your Mac?
GitHub doesn't have the font for it, but Mac should:

<img width="478" alt="Screenshot 2022-11-18 at 09 44 54" src="https://user-images.githubusercontent.com/5754073/202659600-37b5b8e0-c36d-45ad-9122-edc2854994f9.png">

**Comment by maxxfrazer** [comment]
These could instead be changed to use the same as for iOS (camera.fill, mic.slash, etc). But I believe it will require a bump of the minimum macOS from 10.15 to 11, which I wanted to avoid when first making this package.

**Comment by rolf-mobeus** [comment]
@maxxfrazer I understand about the version. Thank you for not moving it to 11. 

I am on Ventura with latest Xcode. When I open the file in Xcode, I see question marks in boxes--like it's a missing glyph. 
<img width="910" alt="image" src="https://user-images.githubusercontent.com/116570073/202729061-c70cd434-3d95-4ffb-bc99-6af31876df4a.png">

**Comment by maxxfrazer** [comment]
that's a pain. if you go to SF Symbols on Ventura and select "copy symbol" on one of them, do you see the same thing of is the char updated? Sorry I haven't made the leap to Ventura just yet.

**Comment by rolf-mobeus** [comment]
Looks like SF Symbols is not included in Ventura by default. I installed SF Symbols 4 using this link, and everything is good now. 

[SF Symbols 4](https://devimages-cdn.apple.com/design/resources/download/SF-Symbols-4.dmg)

I understand your hesitancy to leap--that's a good way to put it. I had to do so for work or I wouldn't be on it yet either!

**Comment by maxxfrazer** [comment]
Thanks for following up! I'll add this to the [VideoUIKit-macOS](https://github.com/AgoraIO-Community/VideoUIKit-macOS) README as a known issue ASAP. I would just make the bump to macOS 11 if it was more widely adopted, alas it isn't.

**Comment by rolf-mobeus** [comment]
No worries. Thank you for the font name, otherwise I wouldn't have found it. 🙂
